name: PROD-DEPLOY

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    timeout-minutes: 3
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Deploy
        run: npx wrangler deploy --minify src/index.ts --env production
